//
// Needle of Tears:
//        Defines
//   By: JackfeldSeinfeld
//

/////////////////////////////////////////
//        W3DNOT VERSION TABLE
//=======================================
//    NOTVER :     |     VERSION:
//=======================================
//       0 :       | ORIGINAL UZI'S DEMO
//=======================================
//       1 :       |    UZI'S DEMO+  
//=======================================

#define NOTVER 1

#ifndef NEEDLEDEMO
#define NOTEXT "NOT"
#else
#ifndef DEV
#define NOTEXT "NDM"
#else
#define NOTEXT "NOT"
#endif
#endif
